name: Create Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
      SUPABASE_PROJECT_ID: ${{ vars.PROJECT_REF_DEV }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase and link project
        run: |
          supabase db start
          supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}

      - name: Ensure migrations directory exists
        run: mkdir -p supabase/migrations

      - name: Fetch changes and test data
        id: fetch
        run: |
          supabase db pull ${{ inputs.release }} -s public,extensions,storage,auth,cron
          supabase db dump --data-only --role-only -s extensions,storage,auth
          supabase db dump --data-only --role-only -s public -f backup.sql

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'Release ${{ inputs.release }}'
          branch: 'release/${{ inputs.release }}'
          base: main
          reviewers: mrkallerud
