name: Deploy to Development

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - supabase/**/*

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ vars.PROJECT_REF }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Production environment
        run: supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}

      - name: Deploy
        run: |
          supabase db push
          supabase functions deploy
