name: Reset development environment

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
      SUPABASE_PROJECT_ID: ${{ vars.PROJECT_REF_DEV }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}
      - run: supabase db reset
