name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    paths:
      - 'supabase/**/*'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: development

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ vars.PROJECT_REF }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run:
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase start

      - name: Run tests
        run: supabase test db

      - name: Check syntax
        run: supabase db lint --error
      
      - name: Check push
        run: supabase db push --dry-run
